"""add password_hash to users

Revision ID: 2ca8f98743a7
Revises: d6771b414b28
Create Date: 2026-08-30 03:00:41.400730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2ca8f98743a7'
down_revision: Union[str, Sequence[str], None] = 'd6771b414b28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###