"""add foreign key user_id to jobs

Revision ID: fde935203ddc
Revises: 2ca8f98743a7
Create Date: 2026-08-30 03:01:58.598129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fde935203ddc'
down_revision: Union[str, Sequence[str], None] = '2ca8f98743a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Only add foreign key constraint, don't alter nullability yet
    # This allows existing NULL rows to remain
    op.create_foreign_key(None, 'jobs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    # ### end Alembic commands ###